### ISSUE TITLE
Got stuck while compiling C/C++ example

### ISSUE THREAD

**Issue by mauringo** [boschrexroth/ctrlx-automation-sdk#11]
Hi, 

I was trying to compile the basic example but i do have a problem with the dependencies: 

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Selected BuildKit: GCC x86_64-linux-gnu
-- ######################################
-- Option: BUILD_SNAP ON
-- ######################################
CMake Error at CMakeLists.txt:88 (include):
  include could not find requested file:

    /home/mauro/ctrlx-automation-sdk-main/samples-cpp/datalayer.provider.all-data/../..//cmake/oss.flatbuffers.1.12/FindFlatBuffers.cmake

CMake Error at CMakeLists.txt:93 (build_flatbuffers):
  Unknown CMake command "build_flatbuffers".

-- Configuring incomplete, errors occurred!
See also "/home/mauro/ctrlx-automation-sdk-main/samples-cpp/datalayer.provider.all-data/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Selected BuildKit: GCC x86_64-linux-gnu
-- ######################################
-- Option: BUILD_SNAP ON
-- ######################################
CMake Error at CMakeLists.txt:88 (include):
  include could not find requested file:

    /home/mauro/ctrlx-automation-sdk-main/samples-cpp/datalayer.provider.all-data/../..//cmake/oss.flatbuffers.1.12/FindFlatBuffers.cmake

CMake Error at CMakeLists.txt:93 (build_flatbuffers):
  Unknown CMake command "build_flatbuffers".

I am not able to find the right dependency missing. 

Mauro

**Comment by albrecht-j** [comment]
Hi @mauringo 
i tried this with my build environment, and it works. 
Maybe you can check if you have the requested files in your filesystem?

In the rootfolder of the SDK there should be a folder called cmake, inside there are different oss.flatbuffers folder. 
If one of them are missing, please reinstall the latest release of the sdk.

Thx for using the ctrlx-automation-sdk :)

Kind Regards
Johannes
