### ISSUE TITLE
Python Datalayer - Float_Array: problems with decimal numbers

### ISSUE THREAD

**Issue by T2FF** [boschrexroth/ctrlx-automation-sdk#12]
Hi ,
I would like to create a node of type float_array64 on the datalayer and have run into a problem. 
The node is created and is also listed and callable in the datalayer via the webinterface of my virtual-core. In my Python script I initialise my node with the values [30.3,180.4,40.5,0.1,0.3,0.2], which are taken over. However, if I now want to change the value of the array via the web interface and execute the write function of the node, all decimal places of my input are ignored or deleted. If I want to change the first value 30.3 to 30.45 and press write, the array looks like this: [30,180,40,0,0,0].

To create the nodes, I created a high-level class based on the python datalayer.calc example: [basic_arithmetic_operations.py](https://github.com/boschrexroth/ctrlx-automation-sdk/blob/main/samples-python/datalayer.calc/calculations/basic_arithmetic_operations.py). For debugging, I printed the value of the variable "data" (via the method get_array_float64) in the "NodeCallback-method": "__on_write". Here, the comma numbers also seem to be ignored: [30.0, 180.0, 40.0, 0.0, 0.0, 0.0]. 

However, if I use the object "Node" in my Python script, which in my case is the instance of the class variant() for the corresponding node, via the method Node.set_array_float64([30.45, 180.0, 40.0, 0.0, 0.0, 0.0]) the value is taken over correctly and also displayed on the datalayer.

I use the 1.14.0 SDK `['ctrlx-datalayer==2.1.0', 'ctrlx-fbs==1.2.0']` in conjunction with Python 3.8.10.
Virtual Core Version: 1.14.1

If needed, I can also upload my script.

**Comment by albrecht-j** [comment]
Hi @T2FF thanks for the Bugreport. We can reproduce it, and we are working on the fix.

Best Regards
Johannes

**Comment by albrecht-j** [comment]
Hi @T2FF we implement the fix, but this was not a problem in the SDK. So the fix will be part of the next release in november or in the next patch.
As you already said, if you use a client directly it work.

Best Regards
Johannes
