### ISSUE TITLE
libc.so.6: version 'GLIBC_2.32/2.33/2.34' not found

### ISSUE THREAD

**Issue by LelandACM** [boschrexroth/ctrlx-automation-sdk#33]
I want upgrade the node and npm lib version.
Now, the node version is: 18.19.0 ,npm version is 10.2.3 
but the samples-node samples can not build success.

**environment：**
sdk: [Release SDK-V-0120]
ctrlx-works-1.20.5

**try to fix it.**
install glibc_3.36 manully, not success, tips: missing some library.

**issues:**
![image](https://github.com/boschrexroth/ctrlx-automation-sdk/assets/19402747/c3d6defb-6bbb-4b75-859e-192ca1720c2e)

**target:**
can use node version 18.XXX

**Comment by albrecht-j** [comment]
hi @LelandACM did you try to build the samples 2.4 with the version 2.4 of ctrlX WORKS? Because the major change from version 1 to 2 was the upgrade from ubuntu20 to ubuntu22

Regards
Johannes

**Comment by LelandACM** [comment]
Can you give me the download address of the latest version of the Ctrlx WORKS software? @albrecht-j

**Comment by NickH16** [comment]
Hi @LelandACM 

ctrlX WORKS you can get from our Collaboration Room. But there are different access levels in the Collaboration Room. If you want to get access to early adopter versions like the version 2.4, you need to be access level 3. 

How to get access, the link to the collaboration room and more information about the level you can find in the [FAQ for ctrlX Store](https://developer.community.boschrexroth.com/t5/Store-and-How-to/FAQ-for-ctrlX-Store/ba-p/23749). 

Regards,

Nick

**Comment by albrecht-j** [comment]
@LelandACM please let me know if this works for you - so we can close this issue

**Comment by LelandACM** [comment]
@albrecht-j ok，thank you
