### ISSUE TITLE
Documentation spelling mistake

### ISSUE THREAD

**Issue by gmantoha** [boschrexroth/ctrlx-automation-sdk#36]
I think this should be `removable-media` instead of `removab1e-media`
![image](https://github.com/boschrexroth/ctrlx-automation-sdk/assets/12948141/dcd58ed5-5b61-4cbe-820b-118d1014c6b8)

Found here:
https://boschrexroth.github.io/ctrlx-automation-sdk/data-exchange.html#configuration-steps

See Snapcraft Docs here:
https://snapcraft.io/docs/removable-media-interface

**Comment by albrecht-j** [comment]
@gmantoha 

Tanks for reporting --> fixed
