### ISSUE TITLE
Documentation should be updated

### ISSUE THREAD

**Issue by gmantoha** [boschrexroth/ctrlx-automation-sdk#37]
This command `curl -s https://raw.githubusercontent.com/boschrexroth/ctrlx-automation-sdk/main/scripts/environment/install-packages.sh | bash` found here: https://github.com/boschrexroth/ctrlx-automation-sdk/blob/main/README.md

should be updated to `curl -s https://raw.githubusercontent.com/boschrexroth/ctrlx-automation-sdk/main/scripts/environment/install-required-packages.sh | bash`

**Comment by albrecht-j** [comment]
Hi @gmantoha we reworked the whole file :)
Thanks for reporting

BR 
Johannes
