### ISSUE TITLE
Build Apps for CtrlX3 and GLIBC 2.39

### ISSUE THREAD

**Issue by lupaulus** [boschrexroth/ctrlx-automation-sdk#42]
Hey, 

How can I adapt this lines to build on Raspabian ? Because `apt update` failed to retrieve this packages.
```
sudo dpkg --add-architecture arm64

DIST="$(lsb_release -sc)"
sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ ${DIST} main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/multiarch-libs.list
sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/multiarch-libs.list
sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/multiarch-libs.list
sudo echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ ${DIST}-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/multiarch-libs.list

# Qualify architecture
sudo sed -i 's/deb http:/deb [arch=amd64] http:/g' /etc/apt/sources.list
```

**Comment by Wishmaster-de** [comment]
@lupaulus 
1. Are you using the 64bit Version of Rasbian? 'uname -a' should help you 
2. Which Pi are you using? The Pi architecture should be arm64/aarch64

So i think you don't have to add the arm64.

**Comment by lupaulus** [comment]
The error when I build with snapcraft :
![image](https://github.com/boschrexroth/ctrlx-automation-sdk/assets/20111917/924d0a5e-da89-4748-b8da-7075dd3e0e4c)

uname -a output (aarch64) :
```
Linux  6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux 
```

Model Name : Raspberry Model PI 4 B

**Comment by Wishmaster-de** [comment]
> The error when I build with snapcraft : ![image](https://private-user-images.githubusercontent.com/20111917/330728125-924d0a5e-da89-4748-b8da-7075dd3e0e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjMyMzUsIm5iZiI6MTcxNTc2MjkzNSwicGF0aCI6Ii8yMDExMTkxNy8zMzA3MjgxMjUtOTI0ZDBhNWUtZGE4OS00NzQ4LWI4ZGEtNzA3NWRkM2UwZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4NDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOWNlMmE5NTdiNWU2MmY0ZmI2ZjQ3ZjRiZTUxODhlMDBlYzcxNTJiYmM3NDY0NzZlM2YwNThlNDIxZGI4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEIX4LY8rYpuw_-pP7Yaj4YEwAo4ywxbDeFz7lowxWA)
> 
> uname -a output (aarch64) :
> 
> ```
> Linux  6.6.28+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux 
> ```
> 
> Model Name : Raspberry Model PI 4 B

You don't have to add the architecture. You can install all packages for the arm64 architecture for building for arm64. The datalayer debian packet includes amd64 (PC) and the arm64 version.

For which architecture are building the project?

**Comment by lupaulus** [comment]
I'm building for arm64 (CtrlX3 target).

I will try

**Comment by Wishmaster-de** [comment]
Could you please provide more information:

- Do you want to create a snap for a example project from the sdk? If yes, which one?
- Wich commands do you execute to build and pack the snap
- Which ctrlx-automation-sdk version are you using?

**Comment by lupaulus** [comment]
> Do you want to create a snap for a example project from the sdk? If yes, which one?

No, from your local project, by my colleague it is working successfully

> Which commands do you execute to build and pack the snap?

```
#!/usr/bin/env bash
set -e
snapcraft clean --destructive-mode
snapcraft --destructive-mode --target-arch=arm64 --enable-experimental-target-arch
```

> Which ctrlx-automation-sdk version are you using? 

ctrlx-automation-sdk github clone from 08/05/2024

**Comment by lupaulus** [comment]
Can we get in Touch ?

**Comment by Wishmaster-de** [comment]
> > Do you want to create a snap for a example project from the sdk? If yes, which one?
> 
> No, from your local project, by my colleague it is working successfully

I' am a little bit confused. Do you want to build a snap from an example from the ctrlx automation sdk or do you have a project of your own?


> 
> > Which commands do you execute to build and pack the snap?
> 
> ```
> #!/usr/bin/env bash
> set -e
> snapcraft clean --destructive-mode
> snapcraft --destructive-mode --target-arch=arm64 --enable-experimental-target-arch
> ```
> 
> > Which ctrlx-automation-sdk version are you using?
> 
> ctrlx-automation-sdk github clone from 08/05/2024

This ctrlx automation sdk is based on Ubuntu core 22.
Your syntax is deprecated and will not work for core22.
You need to use:
` snapcraft pack --build-for=arm64 --verbose`
The --verbose should give you more information in which step the pack process is failing.


Can you share more information of your project? Maybe your snapcraft.yaml?

**Comment by lupaulus** [comment]
![image](https://github.com/boschrexroth/ctrlx-automation-sdk/assets/20111917/f5d993af-df12-4903-aa19-eb4a8de1e65c)

**Comment by lupaulus** [comment]
```
ldd --version
ldd (Ubuntu GLIBC 2.39-0ubuntu8.1) 2.39
```

**Comment by Wishmaster-de** [comment]
> > I' am a little bit confused. Do you want to build a snap from an example from the ctrlx automation sdk or do you have a project of your own?
> 
> It's an own project, that we started building from your example; targetting Ctrlx3 2.2.X
> 

OK. You are using python. I am not an employee of Bosch Rexroth. I thought i could help you as a community member. ;-) I have no experience with python concerning python projects on Ctrlx. I am using mostly c++ and angular. And i am building the c++ projects for amd64 and arm64 (crossbuild).

> > This ctrlx automation sdk is based on Ubuntu core 22.
> > Your syntax is deprecated and will not work for core22.
> 
> Ok, but it is in your sample ... [ctrlx-automation-sdk](https://github.com/boschrexroth/ctrlx-automation-sdk/tree/main)/[samples-python](https://github.com/boschrexroth/ctrlx-automation-sdk/tree/main/samples-python)/[webserver](https://github.com/boschrexroth/ctrlx-automation-sdk/tree/main/samples-python/webserver) /build-snap-arm64.sh
> 
> ![image](https://private-user-images.githubusercontent.com/20111917/332721610-142d5d36-f7aa-4d66-8ed2-5ac033dd1c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzM4MzcsIm5iZiI6MTcxNjM3MzUzNywicGF0aCI6Ii8yMDExMTkxNy8zMzI3MjE2MTAtMTQyZDVkMzYtZjdhYS00ZDY2LThlZDItNWFjMDMzZGQxYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTFiMmY5OGM0ZWE1Mzc1MWUzNjY3NTY4ZWQ2NDllOTVkNWI4YzRhMTJkODExOWJiMzM4MDIzZDQ5ZWQ0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OFm-NXaznSFF7L9HSsVwSzk05QGTdfD1srQA76rRsBI)
> 
Maybe this was forgotten while upgrading to core22. In c++ projects with core22 i was not able to use --target-arch=arm64 --enable-experimental-target-arch 

> snapcraft.yaml :
> 
> ```
> base: core22
> confinement: strict
> grade: stable
> 
> apps:
>   linckdc:
>     command: bin/linckdc
>     plugs:
>       - network
>       - network-bind
>       - datalayer
>       - active-solution
>     daemon: simple
>     passthrough:
>       restart-condition: always
>       restart-delay: 30s
>   
>   publisher:
>     command: bin/publisher
>     plugs:
>       - network
>       - network-bind
>       - datalayer
>       - active-solution
>     daemon: simple
>     passthrough:
>       restart-condition: always
>       restart-delay: 30s
> 
>   web:
>     command: bin/web
>     plugs:
>       - network
>       - network-bind
>       - datalayer
>       - active-solution
>     daemon: simple
>     passthrough:
>       restart-condition: always
>       restart-delay: 30s
> 
>   simulation:
>     command: bin/simulation
>     plugs:
>       - network
>       - network-bind
>       - datalayer
>       - active-solution
>     daemon: simple
>     passthrough:
>       restart-condition: always
>       restart-delay: 30s
> 
> parts:
>   linckdc:
>     plugin: python
>     source: .
>     stage-packages:
>       - libzmq5
>       - ctrlx-datalayer
>   publisher:
>     plugin: python
>     source: .
>     stage:
>       - -lib/python3.*/site-packages/*
>       - -bin/*
>       - -pyvenv.cfg
>   web:
>     plugin: python
>     source: .
>     stage:
>       - -lib/python3.*/site-packages/*
>       - -bin/*
>       - -pyvenv.cfg
>   simulation:
>     plugin: python
>     source: .
>     stage:
>       - -lib/python3.*/site-packages/*
>       - -bin/*
>       - -pyvenv.cfg
>   helper:
>     plugin: python
>     source: .
>     stage:
>       - -lib/python3.*/site-packages/*
>       - -bin/*
>       - -pyvenv.cfg
>   config:
>     plugin: dump
>     source: ./config
>     organize:
>       '*': ./config/
>       '.*': ./config/
>   configs:
>     plugin: dump
>     source: ./configs
>     organize:
>       'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
> 
> plugs:
>   datalayer:
>     interface: content
>     content: datalayer
>     target: $SNAP_DATA/.datalayer
>   active-solution:
>     interface: content
>     content: solutions
>     target: $SNAP_COMMON/solutions
> 
> hooks:
>   connect-plug-active-solution:
>     plugs: [active-solution]
>   remove:
>     plugs: [active-solution]
> 
> slots:
>   package-assets:
>     interface: content
>     content: package-assets
>     source:
>       read:
>       - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
>   package-run:
>     interface: content
>     content: package-run
>     source:
>       write:
>       - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}
> ```

**Comment by Wishmaster-de** [comment]
> I switched on Ubuntu 24.04
> 
> ```
> ldd --version
> ldd (Ubuntu GLIBC 2.39-0ubuntu8.1) 2.39
> ```

Hm, maybe a version problem

> I'm building for arm64 (CtrlX3 target).
> 
> I will try, but why I have this error then when I have all dependencies : ![image](https://private-user-images.githubusercontent.com/20111917/330742286-3439f7ce-5ebf-4d3e-987b-a3e1b54d6259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzM4MzcsIm5iZiI6MTcxNjM3MzUzNywicGF0aCI6Ii8yMDExMTkxNy8zMzA3NDIyODYtMzQzOWY3Y2UtNWViZi00ZDNlLTk4N2ItYTNlMWI1NGQ2MjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDEwMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDA0OGExY2JjMmExZGM1NjljMDJjZGY5ZDBiYjczZDZhODg1MjViMGQyMTQwYjY4ZTg3NWI3YjQyNDRjOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ed_ieXgltc8e4oiz_wSceEi7S0E94kYI10L0tZ78Kdo)

Here GLIBC2.36 and the other GLIBC 2.39.

**Comment by albrecht-j** [comment]
Hi @lupaulus 
i think also that is a Version Problem. If you want to build a snap for CORE X3 Version 2.x you have to build on an Ubuntu Version 22.

Have you tried this?

**Comment by lupaulus** [comment]
No, I will try.

Thanks for the support

**Comment by albrecht-j** [comment]
Okay, thanks.

Please let us know :)

**Comment by lupaulus** [comment]
No warning with Ubuntu 22.04
