### ISSUE TITLE
`ctrlx-datalayer` missing on native Ubuntu SDK

### ISSUE THREAD

**Issue by clausMeko** [boschrexroth/ctrlx-automation-sdk#46]
Hi,

I wanted to use ubuntu on my laptop to develop snaps. I was following your [(simple) instruction](https://boschrexroth.github.io/ctrlx-automation-sdk/setup_ubuntu.html).

However one package `ctrlx-datalayer` is missing when trying to create a sample snap:
```console
(base) ➜  datalayer.client.ext git:(main) ✗ ./build-snap-arm64.sh
Cleaning up priming area
Cleaning up staging area
Cleaning up parts directory
*EXPERIMENTAL* --target-arch for core20 enabled.
Setting target machine to 'arm64'
Failed to fetch stage packages: Error downloading packages for part 'client': The package 'ctrlx-datalayer' was not found..

# confirming it was already installed
(base) ➜  ctrlx-automation-sdk git:(main) ✗ sudo apt install ~/Downloads/ctrlx-datalayer-2.6.1.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'ctrlx-datalayer' instead of '/home/clausbissinger/Downloads/ctrlx-datalayer-2.6.1.deb'
ctrlx-datalayer is already the newest version (2.6.1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
```

Would you please assist to find a solution?

Cheers

**Comment by albrecht-j** [comment]
Hi, 

maybe it helps if you refer directly the path to the datalayer package instead of using it in stage-packages.

which example do you want to build?

**Comment by clausMeko** [comment]
It's working now. I was only executing the scripts mentioned in [readme.md](https://github.com/boschrexroth/ctrlx-automation-sdk/blob/main/README.md).

I was missing mentioned in https://boschrexroth.github.io/ctrlx-automation-sdk/setup_windows_virtualbox_ubuntu.html#dependencies-for-crossbuild-multiarch:
```console
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install libsystemd-dev:arm64
sudo apt-get -y install libsystemd-dev:amd64
sudo apt-get -y install libssl-dev:amd64
sudo apt-get -y install libssl-dev:arm64
sudo apt-get -y install libzmq3-dev:amd64
sudo apt-get -y install libzmq3-dev:arm64
```

Now we can actually build our snaps in a docker ci pipeline...

TY
