### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by clausMeko** [boschrexroth/ctrlx-automation-sdk#50]
Hi,

A colleague and I are thinking about containering your sdk (if we are going to promote ctrlx within our company). The whole `App Build Env` setup + scripts is ok but we think we can make it more convenient.

**However**: 
* are you aware of any fork trying it currently?
* the sdk workflow as it is right now is pretty much how it will remain right? Or are there allready plans to change it?

Cheers,
Claus

**Comment by albrecht-j** [comment]
Hi @clausMeko 

We have also this topic in our backlog for further development.
Yes i think the workflow will remain. Right now, no plans to change it.

Whats your time schedule to do this?

BR
Johannes

**Comment by clausMeko** [comment]
Hi @albrecht-j ,

currently we do not promote it in our company (=>no schedule). I would guess after the first project using ctrlx we would start some prototype. Acceptance would be larger in our company I presume.

I will get back to you when we start it.

ty,
claus
