### ISSUE TITLE
build-fbs.sh script incorrect for dotnet  

### ISSUE THREAD

**Issue by ArcherThompson** [boschrexroth/ctrlx-automation-sdk#51]
in the current main branch of the SDK for dotnet the build-bfs.sh path is
flatc=$(dirname $0)/../../../public/bin/oss.flatbuffers/ubuntu22-gcc-x64/flatc
and should be
flatc=$(dirname $0)/../../bin/oss.flatbuffers/ubuntu22-gcc-x64/release/flatc

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Fixed for next SDK version 3.4.0. Thank you for submitting the bug.

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Fixed for next SDK version 3.4.0.
