### ISSUE TITLE
Installation fails after latest 2.6.2 release (7/30/2024)

### ISSUE THREAD

**Issue by jcsmithf22** [boschrexroth/ctrlx-automation-sdk#54]
I created a new app environment following the latest 2.6.2 release on 7/30/2024. These are the issues I encountered and how I solved them.

The first two installation scripts run fine.

The third script, to install the ctrlX Automation SDK, fails with the following error:

```
ERROR Could not download https://github.com/boschrexroth/ctrlx-automation-sdk/releases/download/2.6.2/ctrlx-automation-sdk-2.6.2.zip
```

The latest release is `ctrlx-automation-sdk-2.6.7.zip` which is different than the release tag, breaking the `clone-install-sdk.sh` script.

This is a simple enough fix:

```diff
# line 68
- ZIP_ARCHIVE=ctrlx-automation-sdk-${TAG}.zip
+ ZIP_ARCHIVE=ctrlx-automation-sdk-2.6.7.zip
```

The script now runs properly. The `ctrlx-datalayer.deb` file is not installed automatically by this version of `clone-install-sdk.sh`  so I tried running the new `install-ctrlx-datalayer.sh` script. I encountered an error with this as well.

```
cd ctrlx-automation-sdk/scripts
./install-ctrlx-datalayer.sh

...

E: Unable to locate package ctrlx-datalayer
```

I tried again, but this time in the `ctrlx-automation-sdk` directory, and this time the application was successfully installed.

```
./scripts/install-ctrlx-datalayer.sh
```

Following this I was able to successfully compile snaps in CPP, Go, Node, and Python without issues. Hopefully these issues are resolved shortly and the temporary workarounds can help anyone else with similar issues.

**Comment by albrecht-j** [comment]
@jcsmithf22 i created a new tag 2.6.7 may you can try again?

Should be fixed
